---
- name: Install nginx
  hosts: all
  become: yes
  tasks: 
    - name: start nginx
      service: 
        name: nginx
        state: started
    - name: Install nginx
      apt:
        name: nginx
        state: present
    