---
- name: Install nginx
  hosts: all
  become: yes
  tasks: 
    - name: Install nginx
      apt:
        name: nginx
        update_cache: yes
        state: present
    - name: start nginx
      service: 
        name: nginx
        state: started