---
- name: Get ready for pet clinic
  hosts: all
  become: yes
  tasks:
    - name: pet clinic pettam bavundhi
      package:
        name: "{{ java_package}}"
        update_cache: yes
        state: present
    - name: ushhh.. antha bavundhi 
      get_url:
        url: https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: /usr/share/spc/spring-petclinic.jar
    - name: araiii e chetha antha entra babu
      file:
        path: /usr/share/spc/
        state: present
    - name: clean cheyaadniki oka panodini pettali 
      user:
        name: spc
        password: 'spc'
    - name: pani vadiki em cheyalo cheppali
      file:
        path: /usr/share/spc/spring-petclinic.jar
        owner: spc
        group: spc
        mode: '0500'
    - name: mari vadiki chata cheepurukatta evali kadha
      copy:
        src: spc.service
        dest: /etc/systemd/system/spc.service
    - name: poyi pani chesukora ani cheppu vadiki
      service:
        name: spc.service
        state: started          
    - name: neat ga pani chesada ledha ani chudali
      debug:
        msg: pora araiii poo.. 8080 port check chey kanipistadu 


